### PR TITLE
fix: precompile revert

### PR DESCRIPTION
**Pull request by dudong2**
Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by cloudgray** [comment]
LGTM!

**Review by cloudgray — APPROVED** [review]
LGTM!

**Review by dongsam — COMMENTED** [review]
How about adding unit tests for the `Revert`, `ProcessPrecompileEvents`, and `AddPrecompileSnapshot`? Although there are integration tests at the app level, these functions are critical and could have severe consequences if they behave even slightly differently than intended, so having unit tests would be beneficial.

**Review by zsystm — APPROVED** [review]
LGTM for changes.

**Comment by dudong2** [comment]
> How about adding unit tests for the `Revert`, `ProcessPrecompileEvents`, and `AddPrecompileSnapshot`? Although there are integration tests at the app level, these functions are critical and could have severe consequences if they behave even slightly differently than intended, so having unit tests would be beneficial.

For the `ProcessPrecompileEvents` function, it is not a critical component. The key is the revert functionality through the `precompileChange` journal. To address this, I have added tests that mimic the actual flow of calling the precompiled contract from a contract.
If this level of testing is sufficient, I will proceed with merging this pr.

**Review by dongsam — APPROVED** [review]

**Pull request merged**
