### PR TITLE
feat: bump up cosmos sdk v0.50.x and cometbft v0.38.0

### PR DESCRIPTION
**Pull request by dudong2**
Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by zsystm** [comment]
I think we should consider updating **[`app/upgrades.go`]** to [latest one](https://github.com/crypto-org-chain/cronos/blob/b2ac3c7de5591e369396f384f44194f68ff5e080/app/upgrades.go) in Cronos ethermint also. 

Cronos added `upgrades.go` in https://github.com/crypto-org-chain/ethermint/pull/278 
and updated it when updating ibc-go to v7.0.1 (https://github.com/crypto-org-chain/ethermint/pull/306)

**Comment by zsystm** [comment]
non-critical & trivial comment: 
Changing string `ethermint_9000-1` to a constant `ChainID`(already defined) would be great.
https://github.com/b-harvest/ethermint/pull/1/files#diff-da38dc05011a3262fbf1f4b208af7960ba5d65f6d739876073904c55118e3764L91

**Comment by dudong2** [comment]
> non-critical & trivial comment: Changing string `ethermint_9000-1` to a constant `ChainID`(already defined) would be great. https://github.com/b-harvest/ethermint/pull/1/files#diff-da38dc05011a3262fbf1f4b208af7960ba5d65f6d739876073904c55118e3764L91

Fixed with reference to crypto-org-chain/ethermint pr(https://github.com/crypto-org-chain/ethermint/pull/278)

**Comment by zsystm** [comment]
**(Resolved)**
suggestion:
When chanID is not set by flag, reading it from config looks great practice.
https://github.com/crypto-org-chain/ethermint/pull/278/files#diff-e5ad063aa68d7aeceef2a6e2756b5fbbe1761c25dcb4722997d35aa527b30b94R253-R268

**Pull request closed without merging**
